name: flutter_chat_composer
description: A modern and versatile chat input component for Flutter, supporting text, voice, and image inputs with a smooth and intuitive user experience.
version: 1.0.0
homepage: https://github.com/superxabc/flutter_chat_composer
repository: https://github.com/superxabc/flutter_chat_composer.git
issue_tracker: https://github.com/superxabc/flutter_chat_composer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  file_picker: ^6.0.0
  connectivity_plus: ^5.0.0
  flutter_sound: ^9.2.13
  path_provider: ^2.1.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/